### ISSUE TITLE
现在似乎失效了

### ISSUE THREAD

**Issue by Nevidebla** [sparanoid/omnibox-ncr#4]
我是刚刚在网上发现这个工具的，但是现在似乎失效了。访问www.google.com然后搜索任意词汇，照样会显示为对应ip地址的地区语言的搜索结果。

**Comment by sparanoid** [comment]
并没有失效，这个工具的作用是在 Omnibox（搜索栏）中实现等价的 No Country Redirect 效果。这个效果只防止域名转向，并不会对你的搜索结果有影响，如果你想从搜索结果中去掉 country-specific content，请在 Google 的搜索设置界面中修改

**Comment by Nevidebla** [comment]
> 并没有失效，这个工具的作用是在 Omnibox（搜索栏）中实现等价的 No Country Redirect 效果。这个效果只防止域名转向，并不会对你的搜索结果有影响，如果你想从搜索结果中去掉 country-specific content，请在 Google 的搜索设置界面中修改

懂了，谢谢
